services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  nextjs-standalone:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-standalone-image
    container_name: projekatios
    environment:
      NODE_ENV: production
      PORT: "3001"
    ports:
      - "3001:3001"
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

  # Bun service (use with: docker compose up nextjs-standalone-with-bun --build)
  nextjs-standalone-with-bun:
    build:
      context: .
      dockerfile: Dockerfile.bun
    image: nextjs-standalone-bun-image
    container_name: projekatios
    environment:
      NODE_ENV: production
      PORT: "30010"
    ports:
      - "3001:3001"
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"